name: 'coverage'
on:
    push:
        branches:
            - master
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                threshold: 60
                skip-step: install